### ISSUE TITLE
编译后，在终端启动程序后，出现的问题。

### ISSUE THREAD

**Issue by H-pf-3058** [BIT-DYN/deeplab_ros#2]
- 大佬你好，我按步骤来的，最后在执行编译后的终端：
/roslaunch img_seg run.launch
出现测试结束的
*****************************************
[test libraries]:

/home/add/anaconda3/envs/net/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
 - cv2.__file__ =  /home/add/anaconda3/envs/net/lib/python3.7/site-packages/cv2/__init__.py
 - sensor_msgs.__file__ =  /opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/__init__.py
 - cv_bridge.__file__ =  /home/add/DeepLabV3Plus_ws/devel/lib/python3.7/site-packages/cv_bridge/__init__.py

*****************************************
[finish test]

- 最后出现了如下报错：
- Resume model from /home/add/DeepLabV3Plus_ws/src/Img_seg_ros/best_deeplabv3plus_mobilenet_cityscapes_os16.pth
libgcc_s.so.1 must be installed for pthread_cancel to work
[img_seg-2] process has died [pid 26036, exit code -6, cmd /home/add/DeepLabV3Plus_ws/src/Img_seg_ros/predict.py __name:=img_seg __log:=/home/add/.ros/log/db4ffd52-e681-11ed-87a3-b025aa4fc88c/img_seg-2.log].
log file: /home/add/.ros/log/db4ffd52-e681-11ed-87a3-b025aa4fc88c/img_seg-2*.log

看了很多说是环境配置的问题，我 ubuntu18.04，python3.7,  pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 cpuonly -c pytorch。
可以看你的相关配置，相关问题可以麻烦劳烦看一下？

**Comment by BIT-DYN** [comment]
我看有人说系统缺少libgcc_s.so.1库
你试一下sudo apt-get install build-essential这个？

**Comment by H-pf-3058** [comment]
> 我看有人说系统缺少libgcc_s.so.1库 你试一下sudo apt-get install build-essential这个？

**感谢您的这么快速回复，刚刚前面环境下：**

build-essential 已经是最新版 (12.4ubuntu1)。
下列软件包是自动安装的并且现在不需要了：
  gir1.2-goa-1.0 gir1.2-snapd-1 linux-headers-5.4.0-42-generic
  linux-hwe-5.4-headers-5.4.0-42 linux-image-5.4.0-42-generic
  linux-modules-5.4.0-42-generic linux-modules-extra-5.4.0-42-generic shim


我现在在试一试老环境：python3.6, pytorch==1.10  cpuonly -c  pytorch。（谢谢您）


GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
问题依旧：
(net) add@add-NUC12SNKi72:~/DeepLabV3Plus_ws$ roslaunch img_seg run.launch
... logging to /home/add/.ros/log/82343116-e68b-11ed-87a3-b025aa4fc88c/roslaunch-add-NUC12SNKi72-5518.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://add-NUC12SNKi72:38519/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    img_seg (img_seg/predict.py)

auto-starting new master
process[master]: started with pid [5547]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 82343116-e68b-11ed-87a3-b025aa4fc88c
process[rosout-1]: started with pid [5577]
started core service [/rosout]
/opt/ros/melodic/lib/python2.7/dist-packages/roslib/packages.py:470: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if resource_name in files:
process[img_seg-2]: started with pid [5581]

*****************************************
	[test libraries]:

/home/add/anaconda3/envs/net/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
 - cv2.__file__ =  /home/add/anaconda3/envs/net/lib/python3.7/site-packages/cv2/__init__.py
 - sensor_msgs.__file__ =  /opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/__init__.py
 - cv_bridge.__file__ =  /home/add/DeepLabV3Plus_ws/devel/lib/python3.7/site-packages/cv_bridge/__init__.py

*****************************************
	[finish test]

Resume model from /home/add/DeepLabV3Plus_ws/src/Img_seg_ros/best_deeplabv3plus_mobilenet_cityscapes_os16.pth
libgcc_s.so.1 must be installed for pthread_cancel to work
[img_seg-2] process has died [pid 5581, exit code -6, cmd /home/add/DeepLabV3Plus_ws/src/Img_seg_ros/predict.py __name:=img_seg __log:=/home/add/.ros/log/82343116-e68b-11ed-87a3-b025aa4fc88c/img_seg-2.log].
log file: /home/add/.ros/log/82343116-e68b-11ed-87a3-b025aa4fc88c/img_seg-2*.log

**Comment by H-pf-3058** [comment]
我编译的时候，相关：

(iss) add@add-NUC12SNKi72:~/DeepLabV3Plus_ws$ catkin init
Catkin workspace `/home/add/DeepLabV3Plus_ws` is already initialized. No action taken.
-------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/add/DeepLabV3Plus_ws
-------------------------------------------------------------------------------
Build Space:        [exists] /home/add/DeepLabV3Plus_ws/build
Devel Space:        [exists] /home/add/DeepLabV3Plus_ws/devel
Install Space:      [unused] /home/add/DeepLabV3Plus_ws/install
Log Space:          [exists] /home/add/DeepLabV3Plus_ws/logs
Source Space:       [exists] /home/add/DeepLabV3Plus_ws/src
DESTDIR:            [unused] None
-------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------------------
Additional CMake Args:       -DPYTHON_EXECUTABLE=/home/add/anaconda3/envs/net/bin/python -DPYTHON_INCLUDE_DIR=/home/add/anaconda3/envs/net/include/python3.7m -DPYTHON_LIBRARY=/home/add/anaconda3/envs/net/lib/libpython3.7m.so -DCMAKE_BUILD_TYPE=Release -DSETUPTOOLS_DEB_LAYOUT=OFF
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------------------


(iss) add@add-NUC12SNKi72:~/DeepLabV3Plus_ws$ -DPYTHON_EXECUTABLE=/home/add/anaconda3/envs/net/bin/python -DPYTHON_INCLUDE_DIR=/home/add/anaconda3/envs/net/include/python3.7m -DPYTHON_LIBRARY=/home/add/anaconda3/envs/net/lib/libpython3.7m.so -DCMAKE_BUILD_TYPE=Release -DSETUPTOOLS_DEB_LAYOUT=OFF
bash: -DPYTHON_EXECUTABLE=/home/add/anaconda3/envs/net/bin/python: 没有那个文件或目录
(iss) add@add-NUC12SNKi72:~/DeepLabV3Plus_ws$ 
(iss) add@add-NUC12SNKi72:~/DeepLabV3Plus_ws$ catkin config  -DPYTHON_EXECUTABLE=/home/add/anaconda3/envs/net/bin/python -DPYTHON_INCLUDE_DIR=/home/add/anaconda3/envs/net/include/python3.7m -DPYTHON_LIBRARY=/home/add/anaconda3/envs/net/lib/libpython3.7m.so -DCMAKE_BUILD_TYPE=Release -DSETUPTOOLS_DEB_LAYOUT=OFF
-------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/add/DeepLabV3Plus_ws
-------------------------------------------------------------------------------
Build Space:        [exists] /home/add/DeepLabV3Plus_ws/build
Devel Space:        [exists] /home/add/DeepLabV3Plus_ws/devel
Install Space:      [unused] /home/add/DeepLabV3Plus_ws/install
Log Space:          [exists] /home/add/DeepLabV3Plus_ws/logs
Source Space:       [exists] /home/add/DeepLabV3Plus_ws/src
DESTDIR:            [unused] None
-------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------------------
Additional CMake Args:       -DPYTHON_EXECUTABLE=/home/add/anaconda3/envs/net/bin/python -DPYTHON_INCLUDE_DIR=/home/add/anaconda3/envs/net/include/python3.7m -DPYTHON_LIBRARY=/home/add/anaconda3/envs/net/lib/libpython3.7m.so -DCMAKE_BUILD_TYPE=Release -DSETUPTOOLS_DEB_LAYOUT=OFF
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------------------





(iss) add@add-NUC12SNKi72:~/DeepLabV3Plus_ws$ catkin build
-------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/add/DeepLabV3Plus_ws
-------------------------------------------------------------------------------
Build Space:        [exists] /home/add/DeepLabV3Plus_ws/build
Devel Space:        [exists] /home/add/DeepLabV3Plus_ws/devel
Install Space:      [unused] /home/add/DeepLabV3Plus_ws/install
Log Space:          [exists] /home/add/DeepLabV3Plus_ws/logs
Source Space:       [exists] /home/add/DeepLabV3Plus_ws/src
DESTDIR:            [unused] None
-------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------------------
Additional CMake Args:       -DPYTHON_EXECUTABLE=/home/add/anaconda3/envs/net/bin/python -DPYTHON_INCLUDE_DIR=/home/add/anaconda3/envs/net/include/python3.7m -DPYTHON_LIBRARY=/home/add/anaconda3/envs/net/lib/libpython3.7m.so -DCMAKE_BUILD_TYPE=Release -DSETUPTOOLS_DEB_LAYOUT=OFF
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------------------
[build] Found '5' packages in 0.0 seconds.                                    
[build] Package table is up to date.                                          
Starting  >>> cv_bridge                                                       
Starting  >>> image_geometry                                                  
Finished  <<< image_geometry                [ 0.2 seconds ]                   
Finished  <<< cv_bridge                     [ 0.2 seconds ]                   
Starting  >>> img_seg                                                         
Starting  >>> opencv_tests                                                    
Finished  <<< img_seg                       [ 0.1 seconds ]                   
Finished  <<< opencv_tests                  [ 0.1 seconds ]                   
[build] Summary: All 4 packages succeeded!                                    
[build]   Ignored:   1 packages were skipped or are blacklisted.              
[build]   Warnings:  None.                                                    
[build]   Abandoned: None.                                                    
[build]   Failed:    None.                                                    
[build] Runtime: 0.4 seconds total.  


有一个包给了warnning，麻烦问一下您，这个会影响？

**Comment by BIT-DYN** [comment]
应该是不影响的，你有什么问题也可以去csdn上评论，说不定有其他人知道答案
https://blog.csdn.net/weixin_43807148/article/details/123489519?spm=1001.2014.3001.5501
